<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetPageProperty("description", "Страница сравнения товаров по характеристикам");
$APPLICATION->SetPageProperty("title", "Сравнение товаров | Дельта-Маркет");
$APPLICATION->SetTitle("Страница сравнения товаров");?><?$APPLICATION->AddChainItem(GetMessage("CATALOG_COMPARE_HEADER_TITLE"));?>
<?$APPLICATION->SetPageProperty("title", GetMessage("CATALOG_COMPARE_HEADER_TITLE"));?>
<?$APPLICATION->SetTitle(GetMessage("CATALOG_COMPARE_HEADER_TITLE"));?>
<?$APPLICATION->AddHeadScript(SITE_TEMPLATE_PATH.'/js/sly.js');?>
<?$APPLICATION->SetPageProperty("HIDE_LEFT_BLOCK", "Y")?>
<?
global $arTheme, $NextSectionID, $arRegion;
if($arRegion)
{
	if($arRegion['LIST_PRICES'])
	{
		if(reset($arRegion['LIST_PRICES']) != 'component')
			$arParams['PRICE_CODE'] = array_keys($arRegion['LIST_PRICES']);
	}
	if($arRegion['LIST_STORES'])
	{
		if(reset($arRegion['LIST_STORES']) != 'component')
			$arParams['STORES'] = $arRegion['LIST_STORES'];
	}
}
if(!in_array('ID', (array)$arParams["COMPARE_OFFERS_FIELD_CODE"]))
	$arParams["COMPARE_OFFERS_FIELD_CODE"][] = 'ID';
?>
<?$APPLICATION->IncludeComponent(
	"bitrix:catalog.compare.result",
	"main",
	Array(
		"ACTION_VARIABLE" => "action",
		"AJAX_MODE" => "Y",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"BASKET_URL" => "/basket/",
		"CACHE_TIME" => "3600000",
		"CACHE_TYPE" => "A",
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO",
		"CONVERT_CURRENCY" => "Y",
		"CURRENCY_ID" => "RUB",
		"DETAIL_URL" => $arResult["FOLDER"].$arResult["URL_TEMPLATES"]["element"],
		"DISPLAY_ELEMENT_SELECT_BOX" => "N",
		"ELEMENT_SORT_FIELD" => "SCALED_PRICE_1",
		"ELEMENT_SORT_FIELD_BOX" => "name",
		"ELEMENT_SORT_FIELD_BOX2" => "id",
		"ELEMENT_SORT_ORDER" => "asc",
		"ELEMENT_SORT_ORDER_BOX" => "asc",
		"ELEMENT_SORT_ORDER_BOX2" => "desc",
		"FIELD_CODE" => array("NAME","PREVIEW_PICTURE"),
		"HIDE_NOT_AVAILABLE" => "N",
		"IBLOCK_ID" => "28",
		"IBLOCK_TYPE" => "aspro_max_catalog",
		"NAME" => "CATALOG_COMPARE_LIST",
		"OFFERS_CART_PROPERTIES" => "",
		"OFFERS_FIELD_CODE" => array("NAME","PREVIEW_PICTURE",""),
		"OFFERS_PROPERTY_CODE" => array(0=>"ARTICLE",1=>"VOLUME",2=>"SIZES",3=>"COLOR_REF",4=>"",),
		"PRICE_CODE" => array("BASE"),
		"PRICE_VAT_INCLUDE" => "Y",
		"PRICE_VAT_SHOW_VALUE" => "N",
		"PRODUCT_ID_VARIABLE" => "id",
		"PROPERTY_CODE" => array("BRAND","COUNTRY_OF_ORIGIN","COLOR","VOLTAGE_LEVEL","POWER","POWER_ALL","SIZE","TRANSPORT_SIZE","WEIGHT","DLINA_MM","WIDTH","HEIGHT","CUTTING_DEPTH","FREQUENCY","MAIN_DRIVE_FREQUENCY","SCORING_DISC_FREQUENCY","MAIN_DRIVE_DIAMETER","SCORING_DISC_DIAMETER","MAIN_DRIVE_POWER","SCORING_DISC_POWER","MAIN_DRIVE_CUTTING_DEPTH","SCORING_DISC_CUTTING_DEPTH","FEED_SPEED_DISC","PROP_2033","COLOR_REF2","MAXIMUM_ROTATION_SPEED","PROP_2065","CUTTER_RADIUS","HEIGHT_EDGE","DEPTH_EDGE","FEED_SPEED_EDGE","CONTAINER_VOLUME","PREHEAT_TIME","WORKING_DIAMETER","SHANK_DIAMETER","PROP_305","PROP_352","PROP_317","PROP_357","PROP_2102","PROP_318","PROP_159","PROP_349","PROP_327","PROP_2052","PROP_370","PROP_336","PROP_2115","PROP_346","PROP_2120","PROP_2053","PROP_363","PROP_320","PROP_2089","PROP_325","PROP_2103","PROP_2085","PROP_300","PROP_322","PROP_362","PROP_365","PROP_359","PROP_284","PROP_364","PROP_356","PROP_343","PROP_2083","PROP_314","PROP_348","PROP_316","PROP_350","PROP_333","PROP_332","PROP_360","PROP_353","TOTAL_LENGTH","PROP_347","PROP_25","PROP_2114","PROP_301","PROP_2101","PROP_2067","PROP_323","PROP_324","PROP_355","PROP_304","PROP_358","PROP_319","PROP_344","PROP_328","PROP_338","PROP_2113","PROP_366","PROP_302","PROP_303","PROP_2054","PROP_341","PROP_223","PROP_283","PROP_354","PROP_313","PROP_2066","PROP_329","PROP_342","PROP_367","PROP_2084","PROP_340","PROP_351","PROP_368","PROP_369","PROP_331","PROP_337","PROP_345","PROP_339","PROP_310","PROP_309","PROP_330","PROP_2017","PROP_335","PROP_321","PROP_308","PROP_206","PROP_334","PROP_2100","PROP_311","PROP_2132","SHUM","PROP_361","PROP_326","PROP_315","PROP_2091","PROP_2026","PROP_307","NUMBER_OF_TEETH","BODY_DISC","VOLUMEKLEY","TIP_KLEYA","FOUNDATION","COLOR_KLEY","WORK_TEMP_KLEY","APPEARANCE","MELTING_INDEX","NOMINAL_VISCOSITY_IN_A_CIRCLE_IUD","VISCOSITY","VISCOSITY_20","VISCOSITY_160","VISCOSITY_170","VISCOSITY_200","DENSITY","SOFTENING_POINT","STRETCHING","INDOOR_TEMPERATURE","BARREL_TEMPERATURE","ROLL_TEMPERATURE","MEMBRANE_TEMPERATURE","ACTIVATION_TEMPERATURE","MINIMUM_FILM_FORMATION_TEMPERATURE","SETTING_TIME","OPEN_TIME","HEAT_RESISTANCE","MOISTURE_OF_BONDED_ELEMENTS","MOVEMENT_SPEED","NOZZLE_DIAMETER","DRYING_TIME","PRESSING_TIME","PH_ISO976","DILUTION","APPLICATION_METHOD","COMPRESSION_PRESSURE","COMPRESSION_SPRAYING","CONSUMPTION","CONSUMPTION2","MASS_FRACTION_OF_RESIDUAL_MONOMER","MASS_FRACTION_OF_DRY_MATTER","HYDROGEN_ION_CONCENTRATION_INDEX","TENSILE_STRENGTH_AT_SEPARATION","FREEZE_RESISTANCE_OF_THE_ADHESIVE","SEDIMENTATION_ON_DILUTION","WORK_TEMP","","","","","","","","","",""),
		"SECTION_ID_VARIABLE" => $arParams["SECTION_ID_VARIABLE"],
		"SHOW_MEASURE" => "Y",
		"SHOW_PRICE_COUNT" => "1",
		"SKU_DETAIL_ID" => "oid",
		"STORES" => array(0=>"",1=>"",),
		"TEMPLATE_THEME" => "blue",
		"USE_PRICE_COUNT" => "N",
		"USE_REGION" => "Y"
	),
$component,
Array(
	'HIDE_ICONS' => 'Y'
)
);?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>