<?if(!defined('B_PROLOG_INCLUDED') || B_PROLOG_INCLUDED !== true)
{
	define("STATISTIC_SKIP_ACTIVITY_CHECK", "true");
	require($_SERVER["DOCUMENT_ROOT"]."/bitrix/modules/main/include/prolog_before.php");
}?>
<?$APPLICATION->IncludeComponent(
	"aspro:wrapper.block.max", 
	".default", 
	array(
		"IBLOCK_TYPE" => "aspro_max_catalog",
		"IBLOCK_ID" => "28",
		"FILTER_NAME" => "arRegionLink",
		"COMPONENT_TEMPLATE" => ".default",
		"SECTION_ID" => "",
		"SECTION_CODE" => "",
		"FILTER_PROP_CODE" => "FAVORIT_ITEM",
		"ELEMENT_SORT_FIELD" => "sort",
		"ELEMENT_SORT_ORDER" => "asc",
		"ELEMENT_SORT_FIELD2" => "id",
		"ELEMENT_SORT_ORDER2" => "desc",
		"INCLUDE_SUBSECTIONS" => "Y",
		"SHOW_ALL_WO_SECTION" => "Y",
		"HIDE_NOT_AVAILABLE" => "N",
		"ELEMENT_COUNT" => "30",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "36000000",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"DISPLAY_COMPARE" => "Y",
		"SHOW_MEASURE" => "Y",
		"DISPLAY_WISH_BUTTONS" => "Y",
		"SHOW_DISCOUNT_PERCENT" => "Y",
		"SHOW_DISCOUNT_PERCENT_NUMBER" => "Y",
		"SHOW_DISCOUNT_TIME" => "Y",
		"SHOW_OLD_PRICE" => "N",
		"PROPERTY_CODE" => array(
			0 => "CML2_ARTICLE",
		),
		"PRICE_CODE" => array(
			0 => "RETAIL",
		),
		"ADD_PROPERTIES_TO_BASKET" => "Y",
		"PRODUCT_PROPERTIES" => array(
			0 => "BRAND",
			1 => "LINK_STAFF",
		),
		"PARTIAL_PRODUCT_PROPERTIES" => "Y",
		"SHOW_RATING" => "Y",
		"STIKERS_PROP" => "HIT",
		"SALE_STIKER" => "SALE_TEXT",
		"CONVERT_CURRENCY" => "Y",
		"TITLE_BLOCK" => "Товар дня",
		"STORES" => array(
			0 => "1",
			1 => "2",
			2 => "3",
			3 => "6",
			4 => "9",
			5 => "",
		),
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO",
		"TITLE_BLOCK_ALL" => "Весь каталог",
		"ALL_URL" => "catalog/",
		"USER_FIELDS" => array(
			0 => "",
			1 => "",
		),
		"FIELDS" => array(
			0 => "",
			1 => "",
		),
		"CURRENCY_ID" => "RUB",
		"SHOW_ONE_CLICK" => "Y",
		"SHOW_GALLERY" => "Y",
		"MAX_GALLERY_ITEMS" => "5",
		"ADD_PICT_PROP" => "MORE_PHOTO1",
		"TOP_DEPTH" => "2",
		"SHOW_ICONS" => "N",
		"SHAPE_PICTURES" => "FROM_THEME",
		"SLIDER_ELEMENTS_COUNT" => "6",
		"LAST_LINK_IN_SLIDER" => "Y",
		"NO_MARGIN" => "Y",
		"FILLED" => "N",
		"SHOW_SUBSECTIONS" => "N",
		"SCROLL_SUBSECTIONS" => "N",
		"INCLUDE_FILE" => "",
		"TITLE_BLOCK_DETAIL_NAME" => "",
		"PAGE_ELEMENT_COUNT" => "4",
		"WIDE_BLOCK" => "N",
		"WIDE_FIRST_BLOCK" => "N",
		"LINE_ELEMENT_COUNT" => "4",
		"VIEW_TYPE" => "HORIZONTAL"
	),
	false
);?>